### ISSUE TITLE
Change of Logical time tag number after zoom in 

### ISSUE THREAD

**Issue by akihitoiwai0912** [densoGSR/lf_test#4]
### Test code
- [Multi_Thread.lf](https://github.com/densoGSR/lf_test/blob/main/Dashboard/src/Multi_Thread.lf)

### Original
![image](https://github.com/user-attachments/assets/80a65320-c0e2-41d8-bdb1-d56a1759d09b)
- a=1
- b=1
- c=1
- d=1
- e=1

### Zoom in first block
![image](https://github.com/user-attachments/assets/46727de5-570f-4947-9459-028da205baf8)
- a=0
- b=0
- c=0
- d=0
- e=0

**Comment by elgeeko1** [comment]
This is expected behavior. There isn't a universal way of visualizing a timeline with color, as it couldn't account for the dense nature of time. We've built the panel here to change opacity of each execution as its reactor's logical clock advances _over the time window shown_.

In this LF application, a timer produces an event every 100ms. All downstream reactors consume events with no logical delay, so all reactions that respond to the event produced by the timer happen in the same logical time step.

In the first image, the duration of the time filter is roughly 300ms, long enough to capture three timer events, and three advances of the logical clock. Each of the three executions shown has a different opacity.

In the second window, the duration of the time filter is roughly 100ms, enough to capture reactions to a single timer event, all of which occur in the same logical timestep. They are all colored with the same opacity.

**Comment by akihitoiwai0912** [comment]
I understand about opacity, but I don't understand why changing the time window changes the logical time number, which is shown on mouse hover, for each reaction. If it's the same LF program, wouldn't the logical time number assignment be the same?

**Comment by elgeeko1** [comment]
The true logical tag is a timestamp, in ns, that will trail physical time. It's a measure of how close to "now" your program is to processing inputs. Representing this in Grafana is difficult since there may be many executions given a time window, and it's also not great at representing timestamps as values.

Instead, we show a relative time index that always begins as '1' for the given time window and increments every time the logical clock advances. It doesn't represent an absolute logical tag, and it doesn't represent by how much the logical clock advances, just a discrete advance of the logical timeline.
